In [2]:
import numpy as np

In [3]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
X_train.shape

(3, 4)

# Z-score Normalization

In [14]:
def zscore_normalize_features(X):
    """
    computes X, zcore normalized by column
    
    Args:
      X (ndarray (m,n))     : input data, m examples, n features
      
    Returns:
      X_norm (ndarray (m,n)): input normalized by column
      mu (ndarray (n,))     : mean of each feature
      sigma (ndarray (n,))  : standard deviation of each feature
    """

    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma

# Mean Normalization

In [20]:
def mean_normalization(X):
    """
    computes X, mean normalization by column
    
    Args:
      X (ndarray (m,n))     : input data, m examples, n features
      
    Returns:
      X_norm (ndarray (m,n)): input normalized by column
      mu (ndarray (n,))     : mean of each feature
      max (ndarray (n,))  : max each feature
      min (ndarray (n,))  : min each feature
    """

    mu = np.mean(X, axis=0)
    max = np.max(X, axis=0)
    min = np.min(X, axis=0)
    X_norm = (X - mu) / (max - min)

    return X_norm, mu, max, min

# Feature Scaling

In [23]:
def feature_scaling(X):
    """
    computes X, feature scaling by column
    
    Args:
      X (ndarray (m,n))     : input data, m examples, n features
      
    Returns:
      X_norm (ndarray (m,n)): input normalized by column
      max (ndarray (n,))  : max each feature
      min (ndarray (n,))  : min each feature
    """

    max = np.max(X, axis=0)
    min = np.min(X, axis=0)
    X_norm = (X - min) / (max - min)

    return X_norm, max, min

In [18]:
X_norm, mu, sigma = zscore_normalize_features(X_train)
X_norm, mu, sigma

(array([[ 1.26311506,  1.33630621, -0.70710678,  1.22474487],
        [-0.08073519, -0.26726124,  1.41421356,  0.        ],
        [-1.18237987, -1.06904497, -0.70710678, -1.22474487]]),
 array([1.45733333e+03, 3.33333333e+00, 1.33333333e+00, 4.00000000e+01]),
 array([5.11961804e+02, 1.24721913e+00, 4.71404521e-01, 4.08248290e+00]))

In [19]:
X_norm, mu, max, min = mean_normalization(X_train)
X_norm, mu, max, min

(array([[ 0.51650692,  0.55555556, -0.33333333,  0.5       ],
        [-0.03301384, -0.11111111,  0.66666667,  0.        ],
        [-0.48349308, -0.44444444, -0.33333333, -0.5       ]]),
 array([1.45733333e+03, 3.33333333e+00, 1.33333333e+00, 4.00000000e+01]),
 array([2104,    5,    2,   45]),
 array([852,   2,   1,  35]))

In [22]:
X_norm, max, min = feature_scaling(X_train)
X_norm, max, min

(array([[1.        , 1.        , 0.        , 1.        ],
        [0.45047923, 0.33333333, 1.        , 0.5       ],
        [0.        , 0.        , 0.        , 0.        ]]),
 array([2104,    5,    2,   45]),
 array([852,   2,   1,  35]))